addressfield_lookup.settings:
  type: config_object
  label: 'Addressfield Lookup settings'
  mapping:
    addressfield_hide_extra_fields:
      type: boolean
    default_service:
      type: string
    cache_length:
      type: integer
