addressfield_lookup.settings:
  type: mapping
  label: Instellingen
  mapping:
    addressfield_lookup_addressfield_hide_extra_fields:
      type: boolean
    addressfield_lookup_default_service:
      type: 'NULL'
